### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by mislav** [mattn/go-colorable#12]
Hi, thanks for this useful project!

Could go-colorable have an open-source license so that we may include, distribute, and modify this project?

Adding a license is easy: just to go the root of the project in the web browser, click "Create new file" button, name the new file something like `LICENSE.md` and the license picker dropdown will appear, letting you pre-populate the license file with text of one of the most popular open source licenses.

Thanks!

**Comment by mislav** [comment]
I just realized the README mentions: "License: MIT". That's great, but it's not enough to legally cover this project with a license. To do that, the project needs to include the full license text. Adding the MIT license text into a `LICENSE` file as I suggested above would be great!

**Comment by mattn** [comment]
done

**Comment by mislav** [comment]
Thanks for the prompt reaction! :+1: :sparkles:
