### ISSUE TITLE
No more color with Windows 10 Anniversary Update build 14393

### ISSUE THREAD

**Issue by hexadecy** [mattn/go-colorable#18]
Since Windows 10 build 14393 ansi color is not enabled by default in CMD.

**Comment by mattn** [comment]
What do you mean `No more color`? This implementation doesn't depend on the feature of ANSI color of cmd.  Please see the code.

**Comment by ViDaNgEr** [comment]
hexadecy is right, go-colorable don't seems to work with the latest flavor of Windows 10

**Comment by hexadecy** [comment]
Ok your are not using ansi, but it's somewhat related to something MS did.
https://github.com/symfony/symfony/issues/19520

**Comment by mattn** [comment]
Yes, I know. But it's optional. https://msdn.microsoft.com/ja-jp/library/windows/desktop/mt638032(v=vs.85).aspx

To use it, should check ENABLE_VIRTUAL_TERMINAL_PROCESSING is enabled with GetConsoleMode. And it still not support 256 color.

go-colorable support pseudo 256 colors using color table. So it have advantage to use go-colorable.

https://github.com/mattn/go-colorable/blob/master/colorable_windows.go#L100
