### ISSUE TITLE
Add SetConsoleTitle support to windows

### ISSUE THREAD

**Issue by Baozisoftware** [mattn/go-colorable#21]
I have
>title:= \033]0;**abcd**\007

use
>fmt.Print(title)

On linux(or mac) os to set the Terminal Title to "**abcd**".but on windows os is don't work.
Windows Console use "SetConsoleTitle" API to do it.

for example(Get inspired from your project,thanks~):
[cmd_title_windows.go](https://github.com/Baozisoftware/Luzhibo-go/blob/master/cmd_title_windows.go) for windows os
[cmd_title_others.go](https://github.com/Baozisoftware/Luzhibo-go/blob/master/cmd_title_others.go) for other os

Sorry,my English are too bad.:)

**Comment by zetamatta** [comment]
@Baozisoftware  Does my patch satisfy your needs ? It has been already merged by mattn. Would you test it ?

**Comment by mattn** [comment]
If you still have this issue, please reopen this.

**Comment by Baozisoftware** [comment]
Thanks for support.
