### ISSUE TITLE
Write escaped text to file

### ISSUE THREAD

**Issue by michael1011** [mattn/go-colorable#25]
Is it somehow possible to write the escaped text to a file? I found *colorable.NewColorable(file \*os.File)* but I was not able to get the output escaped.

**Comment by mattn** [comment]
```go
var out io.Writer = colorable.NewColorableStdout()
```
Do switch `out` simply.
```go
out, _ = os.Create("output")
fmt.Println(out, "\x1b[2J")
```

**Comment by michael1011** [comment]
Thanks
