### ISSUE TITLE
archive not available?

### ISSUE THREAD

**Issue by marcindulak** [mattn/go-colorable#26]
I used to access https://github.com/mattn/go-colorable/archive/d228849504861217f796da67fae4f6e347643f15/go-colorable-d228849.tar.gz directly, but mow getting "curl: (22) The requested URL returned error: 500 Internal Server Error" do you know whether this should still work?

**Comment by mattn** [comment]
Sorry, I don't know it.

**Comment by marcindulak** [comment]
A bit strange, another project which gives me that problem is https://github.com/google/go-github/issues/705 but many other projects have tarballs available as it used to be ...

**Comment by mattn** [comment]
It is issue of github not google or me. You should report it to github.

**Comment by marcindulak** [comment]
Works now, closing.
