### ISSUE TITLE
Aliases for save/restore cursor position 

### ISSUE THREAD

**Issue by filimonov** [mattn/go-colorable#27]
Beside ANSI codes `<esc>[s` (save cursor position) and `<esc>[u` (restore cursor position) there are also widely used DEC code: `<esc>7` and `<esc>8` which do mostly the same, but are preferred sometimes because `<esc>[s` and `<esc>[u` don't work in some terminals like VT100 and Mosh (See https://github.com/mobile-shell/mosh/issues/726)

See also:
"Some terminals require the DEC sequences ESC 7 / ESC 8 instead which is more widely supported." See
https://en.wikipedia.org/wiki/ANSI_escape_code#Examples

See also:
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idsimplecursorpositioningspanspan-idsimplecursorpositioningspanspan-idsimplecursorpositioningspansimple-cursor-positioning

https://vt100.net/docs/vt100-ug/chapter3.html#DECSC

Can you add such an alias?

**Comment by mattn** [comment]
Could you please try this patch?

```diff
diff --git a/colorable_windows.go b/colorable_windows.go
index 15a014f..52a89ab 100644
--- a/colorable_windows.go
+++ b/colorable_windows.go
@@ -471,6 +471,16 @@ loop:
 		w.rest.WriteByte(c2)
 		er.WriteTo(&w.rest)
 
+		// https://github.com/mattn/go-colorable/issues/27
+		if w.rest.Bytes()[2] == '7' {
+			procGetConsoleScreenBufferInfo.Call(uintptr(handle), uintptr(unsafe.Pointer(&csbi)))
+			w.oldpos = csbi.cursorPosition
+			continue
+		} else if w.rest.Bytes()[2] == '8' {
+			procSetConsoleCursorPosition.Call(uintptr(handle), *(*uintptr)(unsafe.Pointer(&w.oldpos)))
+			continue
+		}
+
 		var buf bytes.Buffer
 		var m byte
 		for i, c := range w.rest.Bytes()[2:] {
```

**Comment by filimonov** [comment]
Thanks for patch. Right now i have no windows machine, will test it and confirm at the end of the week.

**Comment by filimonov** [comment]
It doesn't work - few lines before there was a continue statements which skiped that part.

I've created working fix (check pull request https://github.com/mattn/go-colorable/pull/28), but i didn't dig into surrounding code, buffers etc. please recheck if there are no side effects.

**Comment by filimonov** [comment]
Thank you, may be someday other DEC aliases can be set up in the same way.
