### ISSUE TITLE
Please tag on the latest commit

### ISSUE THREAD

**Issue by zetamatta** [mattn/go-colorable#33]
On the working directory for my product which imports go-colorable,

```
set GO111MODULE=on
go get -u
```

go-colorable v0.9.0 is downloaded, but it is too old (commited on 2017) and has some bugs not fixed.

Would you tag the latest commit ?

(For now, I got the latest revision by `go get -m github.com/mattn/go-colorable@efa589957cd060542a26d2dd7832fd6a6c6c3ade` )

**Comment by mattn** [comment]
Tagged v0.1.0

**Comment by zetamatta** [comment]
Thank you!

**Comment by zetamatta** [comment]
( Fixed my typo on this entry: v0.9.0 -> v.0.0.9 )
