### ISSUE TITLE
Cursor movement commands don't default to 1

### ISSUE THREAD

**Issue by ncw** [mattn/go-colorable#39]
According to [my reading](http://www.termsys.demon.co.uk/vtansi.htm) a cursor movment such as `\x1b[A` should be interpreted as `\x1b[1A` so the default movement is 1 character.  This is obeyed by xterms I've tested.

However `\x1b[A` is ignored by go-colorable because of this code

https://github.com/mattn/go-colorable/blob/72ec6f98a4a16d5106d74ec2fa11b14d6c5a28b3/colorable_windows.go#L502-L506

I think this problem affects `A`, `B`, `C`, `D`

Let me know if you would like me to send a patch to fix this.

**Comment by mattn** [comment]
Yes, please do.
