### ISSUE TITLE
Windows colored output is mixed up when running in cmd.exe

### ISSUE THREAD

**Issue by segrey** [mattn/go-colorable#48]
Windows 10 (version 2004)
go version go1.14.2 windows/amd64

Steps to reproduce:

1. Create "mixed-output.go"
```
package main

import (
    "fmt"
    "github.com/mattn/go-colorable"
    "sync"
)

func main() {
    stdout := colorable.NewColorableStdout()
    wg := &sync.WaitGroup{}
    for i := 0; i < 3; i++ {
       wg.Add(1)
       go func() {
           _, _ = fmt.Fprintln(stdout, "\u001b[32mHello\u001b[0m", "World")
           wg.Done()
       }()
    }
    wg.Wait()
}
```

2. Open Command Prompt (cmd.exe) and cd to file's parent folder.
3. `go build mixed-output.go`
4. Run `mixed-output.exe`, the output is mixed.

Mixed output:
![image](https://user-images.githubusercontent.com/607109/80419270-80508080-88e1-11ea-9329-4e9f90ebab70.png)

Works fine in Git bash (MinGW):
![image](https://user-images.githubusercontent.com/607109/80419856-8561ff80-88e2-11ea-91e1-76ec2ce0e58d.png)

**Comment by kolkov** [comment]
Thanks!

**Comment by mattn** [comment]
Thank you too.
