### ISSUE TITLE
tag 0.1.8 doesn't belong to any branch

### ISSUE THREAD

**Issue by priv-kweihmann** [mattn/go-colorable#53]
2e1b0c1546e0173c0907cf05c67b8ba29ed8b4d1 referenced by tag 0.1.8 gives `This commit does not belong to any branch on this repository. ` is that intended behavior?

**Comment by bl-ue** [comment]
@mattn The commit, made on October 3, isn't even on master, or any branch at all. 🤔  The latest on master is from July 26.

**Comment by mattn** [comment]
Sorry. Fixed.
