### ISSUE TITLE
Messed ANSI sequences in terminal output (Windows, cmd.exe, PowerShell) instead of colors

### ISSUE THREAD

**Issue by andreas-kupries** [mattn/go-colorable#58]
This ticket originates in research done for epinio/epinio/issues/673, itself a follow up of epinio/epinio/issues/494

The relevant setup is
  - Platform: Win 10 Home (Virtual Machine, Linux-hosted, VirtualBox)
  - Modules (`grep 'fatih\|mattn' go.mod`):
      - github.com/fatih/color v1.12.0
      - github.com/mattn/go-isatty v0.0.12
  - Sum Modules (`grep 'fatih\|mattn' go.sum |grep -v go.mod`):
      - github.com/fatih/color v1.12.0 h1:mRhaKNwANqRgUBGKmnI5ZxEk7QXmjQeCcuYFMX2bfcc=
      - github.com/mattn/go-colorable v0.1.8 h1:c1ghPdyEDarC70ftn0y+A/Ee++9zz8ljHG1b13eJ0s8=
      - github.com/mattn/go-isatty v0.0.12 h1:wuysRhFDzyxgEmMf5xjvJ2M9dZoWAXNNr5LSBS7uHXY=
      - github.com/mattn/go-runewidth v0.0.7 h1:Ei8KR0497xHyKJPAv59M1dkC+rOZCMBJ+t3fZ+twI54=
    Without excluding `go.mod` lines I see a lot more versions for all the packages.

Below a screenshot demonstrating the differences between a mingw bash (from git for windows) on one side, and cmd.exe and PowerShell on the other side:
![Screenshot](https://user-images.githubusercontent.com/577247/129198305-fd5393d9-7dba-4e77-a358-a4bbf9d74927.png)

While I originally thought that maybe the `IsTerminal` generates an incorrect result, disabling handling with the output from my last tests I now have to suspect an issue either here in `go-colorable`, or in its user, https://github.com/fatih/color, which is the actual package used by the epinio code. And I do not see how our use of the `fatih/color` would be incorrect.

With regard to the version numbers, `fatih/color` is at 1.12.0, the latest release as of May 24 this year.
Which in turn uses the latest tag 0.1.8 for `go-colorable`, as of Oct 3 last year.

Any ideas where else to look for the issue ?

**Comment by mattn** [comment]
go-colorable mimics escape sequence output on Windows. But, it does not hijack os.Stdout or fmt.Printf. You need to do I/O via color.Output. Note that this is fully patch to fix your issues.

```diff
diff --git a/helpers/termui/ui.go b/helpers/termui/ui.go
index 5b03c7d..8d1d9c9 100644
--- a/helpers/termui/ui.go
+++ b/helpers/termui/ui.go
@@ -194,7 +194,7 @@ func (u *Message) Msg(message string) {
 		message = color.RedString(message)
 	}
 
-	fmt.Printf("%s", message)
+	fmt.Fprintf(color.Output, "%s", message)
 
 	for _, interaction := range u.interactions {
 		switch interaction.variant {
@@ -211,17 +211,17 @@ func (u *Message) Msg(message string) {
 		case show:
 			switch interaction.valueType {
 			case tBool:
-				fmt.Printf("%s: %s\n", emoji.Sprint(interaction.name), color.MagentaString("%t", interaction.value))
+				fmt.Fprintf(color.Output, "%s: %s\n", emoji.Sprint(interaction.name), color.MagentaString("%t", interaction.value))
 			case tInt:
-				fmt.Printf("%s: %s\n", emoji.Sprint(interaction.name), color.CyanString("%d", interaction.value))
+				fmt.Fprintf(color.Output, "%s: %s\n", emoji.Sprint(interaction.name), color.CyanString("%d", interaction.value))
 			case tString:
-				fmt.Printf("%s: %s\n", emoji.Sprint(interaction.name), color.GreenString("%s", interaction.value))
+				fmt.Fprintf(color.Output, "%s: %s\n", emoji.Sprint(interaction.name), color.GreenString("%s", interaction.value))
 			}
 		}
 	}
 
 	for idx, headers := range u.tableHeaders {
-		table := tablewriter.NewWriter(os.Stdout)
+		table := tablewriter.NewWriter(color.Output)
 		table.SetHeader(headers)
 		table.SetBorders(tablewriter.Border{Left: true, Top: false, Right: true, Bottom: false})
 		table.SetCenterSeparator("|")
```

**Comment by andreas-kupries** [comment]
Ah! Our use was indeed wrong. Thank you for taking the time to investigate and help.

**Comment by andreas-kupries** [comment]
Confirmed working locally :tada: :fireworks: :green_heart:

**Comment by andreas-kupries** [comment]
Closing as done.
