### ISSUE TITLE
Cross-compile dependency issue

### ISSUE THREAD

**Issue by divan** [mattn/go-colorable#7]
There is a subtle problem with cross-compilation for windows under linux/darwin.
1. `go get github.com/mattn/go-colorable` being run under linux/darwin skips dependencies in file colorable_windows.go, because of "_windows" prefix. This file though has one external dependency - 'github.com/mattn/isatty', which is ignored and isn't downloaded during `go get`.
2. If user want to cross-compile package for windows, `go build` will return error as it has missing dependency:
   `$ GOOS=windows go build github.com/mattn/go-colorable
   colorable_windows.go:13:2: cannot find package "github.com/mattn/go-isatty" in any of:
   /usr/local/go/src/github.com/mattn/go-isatty (from $GOROOT)
   /Users/divan/src/github.com/mattn/go-isatty (from $GOPATH)`
3. Being a general purpose library, it's imported from many more projects, `gin-gonic` among them.
   It ends with users confusion, when he tries to cross-compile package, which depends on go-colorable and it takes time to figure out this issue.

My proposal is to import 'github.com/mattn/isatty' into colorable_others.go as well to allow go get resolve it as dependency regardless of which platform is used.
`+  _ "github.com/mattn/go-isatty"`

**Comment by mattn** [comment]
you need to `go get github.com/mattn/go-isatty` with GOOS=windows.

**Comment by divan** [comment]
Yes, that'll solve the problem. But the question is how to make dependent packages go get & cross-build as expected.

Again, the real case was (not mine, btw) a user willing to crosscompile gin-based http-service.
Normal workflow would be:
 - `go get github.com/gin-gonic/gin`
 -  `GOOS=windows go build`

Instead, user gets confusing errors, and have to spend some time to identify the source of the problem (we're all used to the fact go packages build cleanly), which is a bit tricky, especially for newcomers.

A guy who initially asked me for help, had spent 1 hour trying to figure our why gin-based service doesn't build.

I believe this situation can be avoided for other users.

**Comment by mattn** [comment]
> go get github.com/gin-gonic/gin
> GOOS=windows go build

workflow should be 

GOOS=windows go get github.com/gin-gonic/gin
GOOS=windows go build

I think.

**Comment by divan** [comment]
Well, articles and tutorials on cross-compilation for Go do not tell users to 'go get' with GOOS flag.
Tools like goxc do not run 'go get' either.

So, each user facing this would have to spend time understanding cause of the problem and it's not obvious (not like they get message "Run go get with GOOS flag" or so).

Any downsides of putting import into colorable_others.go?

**Comment by bictorman** [comment]
FWIW, I had the same issue and ended up [adding the conditional import to my own package](https://github.com/comail/wincolog/blob/master/wincolog.go#L8). But I agree, it would make sense to add it in colorable_others.go. Ideally, the go tool should provide a flag to `go get` all os/architectures, but it doesn't.

**Comment by painhardcore** [comment]
I had this issue and stuck for 30 minuts to figure it out. It's better to import modules for all platforms for best cross-compile experience

**Comment by computermouth** [comment]
Ping,

Glad this issue exists, or I would have never figured this out.

Thanks @divan

**Comment by mattn** [comment]
I'm still not convinced but fix because some one reported this issue.

**Comment by computermouth** [comment]
Not convinced? I can recreate the exact conditions and send you a link to a test repository if you like, but it sounds like the issue won't appear unless you're cross compiling from a non-Windows machine.

**Comment by divan** [comment]
Thanks @mattn, it's definitely not the critical/stopper issue, and cross compiling is a minority of use cases, obviously. There is a workaround for the issue, but the biggest problem is that there is no easy way to find this workaround.

What is your concern about the fix, btw? Any trade-offs/sacrifaces here?

Maybe it's worth to discuss this issue with Go team, should `go get` download deps for other dependencies as well?
